<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-30 at 14:28:06.
 */
require_once '../classes/Comment.php';

class CommentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Comment
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Comment(1, 1, 1, "nice", "2017-04-28 01:00:43", 1);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * @covers Comment::getCommentID
     * @todo   Implement testGetCommentID().
     * @test
     */
    public function GetCommentID() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                1, $this->object->getCommentID()
        );
    }

    /**
     * @covers Comment::setCommentID
     * @todo   Implement testSetCommentID().
     * @test
     */
    public function SetCommentID() {
        $this->object->setCommentID(1);
        $this->assertEquals(
                1, $this->object->getCommentID()
        );
    }
    
    /**
     * @covers Comment::getIsFiltered
     * @todo   Implement testGetIsFiltered().
     * @test
     */
    public function GetIsFiltered() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                1, $this->object->getIsFiltered()
        );
    }

    /**
     * @covers Comment::setIsFilteredID
     * @todo   Implement testSetIsFilteredID().
     * @test
     */
    public function SetIsFiltered() {
        $this->object->setIsFiltered(1);
        $this->assertEquals(
                1, $this->object->getIsFiltered()
        );
    }

    /**
     * @covers Comment::getPostID
     * @todo   Implement testGetPostID().
     * @test
     */
    public function GetPostID() {
        $this->assertEquals(
                1, $this->object->getPostID()
        );
    }

    /**
     * @covers Comment::getUserID
     * @todo   Implement testGetUserID().
     * @test
     */
    public function GetUserID() {
        $this->assertEquals(
                1, $this->object->getUserID()
        );
    }

    /**
     * @covers Comment::getComment
     * @todo   Implement testGetComment().
     * @test
     */
    public function GetComment() {
        $this->assertEquals(
                "nice", $this->object->getComment()
        );
    }

    /**
     * @covers Comment::getTime
     * @todo   Implement testGetTime().
     * @test
     */
    public function GetTime() {
        $this->assertEquals(
                "2017-04-28 01:00:43", $this->object->getTime()
        );
    }

    /**
     * @covers Comment::setPostID
     * @todo   Implement testSetPostID().
     * @test
     */
    public function SetPostID() {
        $this->object->setPostID(1);
        $this->assertEquals(
                1, $this->object->getCommentID()
        );
    }

    /**
     * @covers Comment::setUserID
     * @todo   Implement testSetUserID().
     * @test
     */
    public function SetUserID() {
        $this->object->setUserID(1);
        $this->assertEquals(
                1, $this->object->getUserID()
        );
    }

    /**
     * @covers Comment::setComment
     * @todo   Implement testSetComment().
     * @test
     */
    public function SetComment() {
        $this->object->setComment("nice");
        $this->assertEquals(
                "nice", $this->object->getComment()
        );
    }

    /**
     * @covers Comment::setTime
     * @todo   Implement testSetTime().
     * @test
     */
    public function SetTime() {
        $this->object->setComment("2017-04-28 01:00:43");
        $this->assertEquals(
                "2017-04-28 01:00:43", $this->object->getTime()
        );
    }

    /**
     * @covers Comment::diplayComment
     * @todo   Implement testDiplayComment().
     */
    public function testDiplayComment() {
        $this->expectOutputString("");
        $this->object->diplayComment();
    }

}
