<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-30 at 16:17:50.
 */
require_once '../classes/Post.php';

class PostTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Post
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Post(1,2,"test","test","test.jpg",1,0,"2017-04-30 14:20:59","test,",1,"");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
                unset($this->object);

    }

    /**
     * testGetUserID
     * 
     * Test the GetUserID method
     * @todo   Implement testGetUserID().
     */
    public function testGetUserID()
    {
        $this->assertEquals(2,  $this->object->getUserID()
        );
    }

    /**
     * @covers Post::getPostID
     * @todo   Implement testGetPostID().
     */
    public function testGetPostID()
    {
         $this->assertEquals(1,  $this->object->getPostID()
        );
    }

    /**
     * @covers Post::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle()
    {
         $this->assertEquals("test",  $this->object->getTitle()
        );
    }

    /**
     * @covers Post::getContent
     * @todo   Implement testGetContent().
     */
    public function testGetContent()
    {
         $this->assertEquals("test",  $this->object->getContent()
        );
    }

    /**
     * @covers Post::getTime
     * @todo   Implement testGetTime().
     */
    public function testGetTime()
    {
        $this->assertEquals("2017-04-30 14:20:59",  $this->object->getTime()
        );
    }

    /**
     * @covers Post::getPicName
     * @todo   Implement testGetPicName().
     */
    public function testGetPicName()
    {
        $this->assertEquals("test.jpg",  $this->object->getPicName()
        );
    }

    /**
     * @covers Post::getNo_like
     * @todo   Implement testGetNo_like().
     */
    public function testGetNo_like()
    {
        $this->assertEquals(1,  $this->object->getNo_like()
        );
    }

    /**
     * @covers Post::getNo_dislike
     * @todo   Implement testGetNo_dislike().
     */
    public function testGetNo_dislike()
    {
       $this->assertEquals(0,  $this->object->getNo_dislike()
        );
    }

    /**
     * @covers Post::getHashtag
     * @todo   Implement testGetHashtag().
     */
    public function testGetHashtag()
    {
        $this->assertEquals("test,",  $this->object->getHashtag()
        );
    }

    /**
     * @covers Post::setUserID
     * @todo   Implement testSetUserID().
     */
    public function testSetUserID()
    {
        $this->object->setUserID(1);
        $this->assertEquals( 1,  $this->object->getUserID()
        );
    }

    /**
     * @covers Post::setPostID
     * @todo   Implement testSetPostID().
     */
    public function testSetPostID()
    {
       $this->object->setUserID(2);
        $this->assertEquals( 2,  $this->object->getPostID()
        );
    }

    /**
     * @covers Post::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
       $this->object->setTitle("test1");
        $this->assertEquals( "test1",  $this->object->getTitle()
        );
    }

    /**
     * @covers Post::setContent
     * @todo   Implement testSetContent().
     */
    public function testSetContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::setTime
     * @todo   Implement testSetTime().
     */
    public function testSetTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::setPicName
     * @todo   Implement testSetPicName().
     */
    public function testSetPicName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::setNo_like
     * @todo   Implement testSetNo_like().
     */
    public function testSetNo_like()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::setNo_dislike
     * @todo   Implement testSetNo_dislike().
     */
    public function testSetNo_dislike()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::setHashtag
     * @todo   Implement testSetHashtag().
     */
    public function testSetHashtag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::getAllowComment
     * @todo   Implement testGetAllowComment().
     */
    public function testGetAllowComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::setAllowComment
     * @todo   Implement testSetAllowComment().
     */
    public function testSetAllowComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::getFilter_keyword
     * @todo   Implement testGetFilter_keyword().
     */
    public function testGetFilter_keyword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::setFilter_keyword
     * @todo   Implement testSetFilter_keyword().
     */
    public function testSetFilter_keyword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::displayAtHome
     * @todo   Implement testDisplayAtHome().
     */
    public function testDisplayAtHome()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::displayTileInList
     * @todo   Implement testDisplayTileInList().
     */
    public function testDisplayTileInList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::displayAtAllPost
     * @todo   Implement testDisplayAtAllPost().
     */
    public function testDisplayAtAllPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::displayAtDetail
     * @todo   Implement testDisplayAtDetail().
     */
    public function testDisplayAtDetail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::displayPostComments
     * @todo   Implement testDisplayPostComments().
     */
    public function testDisplayPostComments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
