<?php
require_once '../classes/User.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-30 at 17:00:43.
 */
class UserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new User(1,"kyle","Iam12345678","kyle@gmail.com","MALE","profile.png","about myself");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * testGetDescription
     * @group Getter&Stter
     * Test the GetDescription method
     * 
     */
    public function testGetDescription() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                "about myself", $this->object->getDescription()
        );
    }

    /**
     * testGetUserID
     * @group Getter&Stter
     * Test the GetUserID method
     * 
     */
    public function testGetUserID() {
        // Remove the following lines when you implement this test.
         $this->assertEquals(
                1, $this->object->getUserID()
        );
    }

    /**
     * testGetName
     * @group Getter&Stter
     * Test the GetName method
     * 
     */
    public function testGetName() {
         $this->assertEquals(
                "kyle",$this->object->getName()
        );
    }

    /**
     * testGetPassword
     * @group Getter&Stter
     * Test the GetPassword method
     * 
     */
    public function testGetPassword() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                "Iam12345678",$this->object->getPassword()
        );
    }

    /**
     * testGetEmail
     * @group Getter&Stter
     * Test the GetEmail method
     * 
     */
    public function testGetEmail() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                "kyle@gmail.com",$this->object->getEmail()
        );
    }

    /**
     * testGetGender
     * @group Getter&Stter
     * Test the GetGender method
     * 
     */
    public function testGetGender() {
        $this->assertEquals(
                "MALE",$this->object->getGender()
        );
    }

    /**
     * testGetProfilePic
     * @group Getter&Stter
     * Test the GetProfilePic method
     * 
     */
    public function testGetProfilePic() {
        $this->assertEquals(
                "profile.png",$this->object->getProfilePic()
        );
    }

    /**
     * testSetUserID
     * @group Getter&Stter
     * Test the SetUserID method
     * 
     */
    public function testSetUserID() {
        $this->object->setUserID(2);
         $this->assertEquals(
                2, $this->object->getUserID()
        );
    }

    /**
     * testSetName
     * @group Getter&Stter
     * Test the SetName method
     * 
     */
    public function testSetName() {
         $this->object->setUserID("li");
         $this->assertEquals(
                "li", $this->object->getName()
        );
    }

    /**
     * testSetPassword
     * @group Getter&Stter
     * Test the SetPassword method
     * 
     */
    public function testSetPassword() {
        $this->object->setPassword("Iam87654321");
         $this->assertEquals(
                "Iam87654321", $this->object->getPassword()
        );
    }

    /**
     * testSetEmail
     * @group Getter&Stter
     * Test the SetEmail method
     * 
     */
    public function testSetEmail() {
        $this->object->setEmail("li@gmail.com");
         $this->assertEquals(
                "li@gmail.com", $this->object->getEmail()
        );
    }

     /**
     * testSetGender
     * @group Getter&Stter
     * Test the SetGender method
     * 
     */
    public function testSetGender() {
        $this->object->setGender("FEMALE");
         $this->assertEquals(
                "FEMALE", $this->object->getGender()
        );
    }

    /**
     * testSetDescription
     * @group Getter&Stter
     * Test the SetDescription method
     * 
     */
    public function testSetDescription() {
        $this->object->setDescription("hahahaha");
         $this->assertEquals(
                "hahahaha", $this->object->getDescription()
        );
    }

    /**
     * testSetProfilePic
     * @group Getter&Stter
     * Test the SetProfilePic method
     * 
     */
    public function testSetProfilePic() {
        $this->object->setProfilePic("");
         $this->assertEquals(
                "", $this->object->getProfilePic()
        );
    }

    /**
     * testDisplayProfilePic
     * @group display
     * Test the DisplayProfilePic method
     * 
     */
    public function testDisplayProfilePic() {
        $expected = '<center><img class="img-responsive visible-lg profile-pic" src="img/' . $this->object->getProfilePic() . '" alt="" style="height:250px;"/></center>
                    <center><img class="img-responsive visible-md profile-pic" src="img/' . $this->object->getProfilePic() . '" alt="" style="height:250px;"/></center>
                    <center><img class="img-responsive visible-sm profile-pic" src="img/' . $this->object->getProfilePic() . '" alt="" style="width: 50%;height:250px;"/></center>
                    <center><img class="img-responsive visible-xs profile-pic" src="img/' . $this->object->getProfilePic() . '" alt="" style="width: 50%; height:180px;"/></center>';

        $this->asserEquals($expected, $this->object->displayProfilePic()
        );
    }

}