<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-30 at 17:01:07.
 */
class UtilityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Utility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Utility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Utility::formatDate
     * @todo   Implement testFormatDate().
     */
    public function testFormatDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::changeToHashTag
     * @todo   Implement testChangeToHashTag().
     */
    public function testChangeToHashTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::splitStringByDelimiter
     * @todo   Implement testSplitStringByDelimiter().
     */
    public function testSplitStringByDelimiter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::filterCommentByKeyword
     * @todo   Implement testFilterCommentByKeyword().
     */
    public function testFilterCommentByKeyword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::getFilteredComment
     * @todo   Implement testGetFilteredComment().
     */
    public function testGetFilteredComment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
